# Generated by Django 3.1.2 on 2020-10-15 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classlinks', '0003_auto_20201016_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('created_at', models.DateField(auto_now=True)),
                ('classlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classlinks.classlink')),
            ],
        ),
    ]
