# Generated by Django 3.1.2 on 2020-10-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='enrolled',
            field=models.IntegerField(default=0),
        ),
    ]
