# Generated by Django 3.1.2 on 2020-10-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_batch_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lastpayment',
        ),
    ]
