# Generated by Django 3.1.2 on 2020-11-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201020_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='accounts/Screenshot_18.png', upload_to='accounts/'),
        ),
    ]
