# Generated by Django 3.1.2 on 2020-10-15 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classlinks', '0002_classtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='name',
        ),
        migrations.CreateModel(
            name='ClassLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classdate', models.DateField()),
                ('url', models.URLField()),
                ('created_at', models.DateField(auto_now=True)),
                ('classtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classlinks.classtime')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classlinks.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
