# Generated by Django 3.1.2 on 2020-11-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classlinks', '0004_subject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlink',
            name='teacher',
        ),
    ]
